# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-03 23:01
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('estudiante', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Administrador',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Bus',
            fields=[
                ('cod_bus', models.CharField(max_length=3, primary_key=True, serialize=False)),
                ('capacidad', models.IntegerField(max_length=2)),
            ],
        ),
        migrations.CreateModel(
            name='Conductor',
            fields=[
                ('id_c', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('nombre_c', models.CharField(max_length=30)),
                ('apellido_c', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Paradero',
            fields=[
                ('cod_p', models.CharField(max_length=3, primary_key=True, serialize=False)),
                ('nombre_p', models.CharField(max_length=30)),
                ('direccion', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Posee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cod_p', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='administrador.Paradero')),
            ],
        ),
        migrations.CreateModel(
            name='Ruta',
            fields=[
                ('nombre_r', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('cod_bus', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='administrador.Bus')),
                ('paraderos', models.ManyToManyField(through='administrador.Posee', to='administrador.Paradero')),
            ],
        ),
        migrations.CreateModel(
            name='Toma',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hora', models.CharField(choices=[('11', '11:00 AM'), ('12', '12:00 PM'), ('5', '05:00 PM'), ('6', '06:00 PM')], max_length=2)),
                ('fecha', models.DateField(max_length=20)),
                ('codigo_e', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='estudiante.Estudiante')),
                ('nombre_r', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='administrador.Ruta')),
            ],
        ),
        migrations.AddField(
            model_name='posee',
            name='nombre_r',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='administrador.Ruta'),
        ),
        migrations.AddField(
            model_name='bus',
            name='id_c',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='administrador.Conductor'),
        ),
        migrations.AlterUniqueTogether(
            name='toma',
            unique_together=set([('hora', 'fecha', 'nombre_r', 'codigo_e')]),
        ),
    ]
