# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-03 23:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administrador', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bus',
            name='capacidad',
            field=models.IntegerField(),
        ),
    ]
