# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-10 16:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administrador', '0002_auto_20170603_1803'),
    ]

    operations = [
        migrations.AlterField(
            model_name='toma',
            name='fecha',
            field=models.DateField(auto_now_add=True, max_length=20),
        ),
    ]
