# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-10 21:09
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('estudiante', '0005_auto_20170610_1500'),
        ('administrador', '0003_auto_20170610_1151'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='toma',
            unique_together=set([('hora', 'fecha', 'codigo_e')]),
        ),
    ]
