# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-03 22:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Estudiante',
            fields=[
                ('codigo_e', models.CharField(max_length=9, primary_key=True, serialize=False)),
                ('nombre_e', models.CharField(max_length=30)),
                ('apellido_e', models.CharField(max_length=30)),
            ],
        ),
    ]
