# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-12 19:57
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Estudiante',
            fields=[
                ('codigo_e', models.CharField(max_length=9, primary_key=True, serialize=False, validators=[django.core.validators.RegexValidator(message='El codigo debe ser numerico', regex='^[0-9]*$')])),
                ('nombre_e', models.CharField(max_length=30, validators=[django.core.validators.RegexValidator(message='El nombre no debe contener numeros', regex='^[a-zA-Z ]*$')])),
                ('apellido_e', models.CharField(max_length=30, validators=[django.core.validators.RegexValidator(message='El Apellido no debe contener numeros', regex='^[a-zA-Z ]*$')])),
            ],
        ),
    ]
