# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-10 16:51
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estudiante', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='estudiante',
            name='codigo_e',
            field=models.CharField(max_length=9, primary_key=True, serialize=False, validators=[django.core.validators.RegexValidator(message='Solo numeros', regex='^[0-9]*$')]),
        ),
    ]
