# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-10 16:54
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estudiante', '0002_auto_20170610_1151'),
    ]

    operations = [
        migrations.AlterField(
            model_name='estudiante',
            name='codigo_e',
            field=models.CharField(max_length=9, primary_key=True, serialize=False, validators=[django.core.validators.RegexValidator(message='El codigo debe ser numerico', regex='^[0-9]*$')]),
        ),
        migrations.AlterField(
            model_name='estudiante',
            name='nombre_e',
            field=models.CharField(max_length=30, validators=[django.core.validators.RegexValidator(message='El nombre no debe contener numeros', regex='^[a-zA-Z]*$')]),
        ),
    ]
