# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-10 16:58
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estudiante', '0003_auto_20170610_1154'),
    ]

    operations = [
        migrations.AlterField(
            model_name='estudiante',
            name='apellido_e',
            field=models.CharField(max_length=30, validators=[django.core.validators.RegexValidator(message='El nombre no debe contener numeros', regex='^[a-zA-Z ]*$')]),
        ),
        migrations.AlterField(
            model_name='estudiante',
            name='nombre_e',
            field=models.CharField(max_length=30, validators=[django.core.validators.RegexValidator(message='El nombre no debe contener numeros', regex='^[a-zA-Z ]*$')]),
        ),
    ]
